namespace VisionAssist.Overlay;

/// <summary>
/// Interface text in the three languages the rest of the project already
/// supports. A missing key falls back to English rather than showing the key,
/// so a half-translated build is still usable.
/// </summary>
internal static class Strings
{
    public static string Language { get; set; } = "uz";

    public static readonly string[] Languages = { "uz", "ru", "en" };

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["uz"] = new()
        {
            ["health"] = "JON",
            ["armor"] = "ZIRH",
            ["weapon"] = "QUROL",
            ["round"] = "RAUND",
            ["money"] = "PUL",
            ["waiting"] = "KUTILMOQDA",
            ["noGame"] = "O'YIN YOPIQ",
            ["menu"] = "MENYU",
            ["freezetime"] = "TAYYORLANISH",
            ["live"] = "RAUND",
            ["over"] = "RAUND TUGADI",
            ["warmup"] = "QIZDIRISH",
            ["paused"] = "TO'XTATILDI",
            ["bomb"] = "BOMBA",
            ["defusePhase"] = "ZARARSIZLANTIRISH",
            ["bombPlanted"] = "BOMBA QO'YILDI",
            ["burning"] = "YONAYAPSIZ",
            ["blind"] = "KO'ZINGIZ KO'RMAYDI",
            ["smoked"] = "TUTUN ICHIDA",
            ["defused"] = "ZARARSIZLANTIRILDI",
            ["exploded"] = "BOMBA PORTLADI",
            ["defuseYes"] = "YETADI",
            ["defuseNo"] = "YETMAYDI",
            ["kit"] = "KIT",
            ["hasBomb"] = "BOMBA SIZDA",
            ["helmet"] = "kaska",
            ["noWeapon"] = "yo'q",
            ["left"] = "CHAP",
            ["right"] = "O'NG",
            ["soundOff"] = "OVOZ O'CHIRILGAN",
            ["soundStarting"] = "ISHGA TUSHIRILMOQDA",
            ["soundSilent"] = "OVOZ KELMAYAPTI",
            ["soundNoBlocks"] = "OVOZ O'LCHAGICH ISHLAMADI",
            ["soundMono"] = "OVOZ MONO - YO'NALISH YO'Q",
            ["settings"] = "Sozlamalar",
            ["settingsHint"] = "Alt bosilsa shu oyna ochiladi va yopiladi",
            ["language"] = "Til",
            ["theme"] = "Rang to'plami",
            ["size"] = "O'lcham",
            ["corner"] = "Joylashuv",
            ["opacity"] = "Shaffoflik",
            ["sound"] = "Ovoz yo'nalishi",
            ["sensitivity"] = "Sezgirlik",
            ["on"] = "Yoqilgan",
            ["off"] = "O'chirilgan",
            ["close"] = "Yopish",
            ["quit"] = "Dasturdan chiqish",
            ["topLeft"] = "Yuqori chap",
            ["topRight"] = "Yuqori o'ng",
            ["bottomLeft"] = "Pastki chap",
            ["bottomRight"] = "Pastki o'ng",
            ["onlyOwnData"] = "Faqat o'zingizning holatingiz ko'rsatiladi. Dushman joylashuvi yo'q.",
            ["gsiMissing"] = "O'yin ma'lumot yubormayapti. cfg qo'yilganmi va CS2 qayta ishga tushirilganmi?",
            ["audioError"] = "Ovozni yoqib bo'lmadi",
            ["alreadyRunning"] = "VisionAssist Overlay allaqachon ishlab turgan.",
            ["portBusy"] = "Port band. Companion dasturi ochiq bo'lsa uni yoping.",
        },
        ["ru"] = new()
        {
            ["health"] = "ЗДОРОВЬЕ",
            ["armor"] = "БРОНЯ",
            ["weapon"] = "ОРУЖИЕ",
            ["round"] = "РАУНД",
            ["money"] = "ДЕНЬГИ",
            ["waiting"] = "ОЖИДАНИЕ",
            ["noGame"] = "ИГРА ЗАКРЫТА",
            ["menu"] = "МЕНЮ",
            ["freezetime"] = "ПОДГОТОВКА",
            ["live"] = "РАУНД",
            ["over"] = "РАУНД ОКОНЧЕН",
            ["warmup"] = "РАЗМИНКА",
            ["paused"] = "ПАУЗА",
            ["bomb"] = "БОМБА",
            ["defusePhase"] = "РАЗМИНИРОВАНИЕ",
            ["bombPlanted"] = "БОМБА УСТАНОВЛЕНА",
            ["burning"] = "ВЫ ГОРИТЕ",
            ["blind"] = "ВЫ ОСЛЕПЛЕНЫ",
            ["smoked"] = "В ДЫМУ",
            ["defused"] = "РАЗМИНИРОВАНА",
            ["exploded"] = "БОМБА ВЗОРВАЛАСЬ",
            ["defuseYes"] = "ХВАТАЕТ",
            ["defuseNo"] = "НЕ ХВАТИТ",
            ["kit"] = "НАБОР",
            ["hasBomb"] = "БОМБА У ВАС",
            ["helmet"] = "шлем",
            ["noWeapon"] = "нет",
            ["left"] = "ЛЕВО",
            ["right"] = "ПРАВО",
            ["soundOff"] = "ЗВУК ВЫКЛЮЧЕН",
            ["soundStarting"] = "ЗАПУСК",
            ["soundSilent"] = "ЗВУК НЕ ПОСТУПАЕТ",
            ["soundNoBlocks"] = "ИЗМЕРИТЕЛЬ НЕ ЗАПУСТИЛСЯ",
            ["soundMono"] = "ЗВУК МОНО - НЕТ НАПРАВЛЕНИЯ",
            ["settings"] = "Настройки",
            ["settingsHint"] = "Нажатие Alt открывает и закрывает это окно",
            ["language"] = "Язык",
            ["theme"] = "Цветовая схема",
            ["size"] = "Размер",
            ["corner"] = "Расположение",
            ["opacity"] = "Прозрачность",
            ["sound"] = "Направление звука",
            ["sensitivity"] = "Чувствительность",
            ["on"] = "Включено",
            ["off"] = "Выключено",
            ["close"] = "Закрыть",
            ["quit"] = "Выйти из программы",
            ["topLeft"] = "Сверху слева",
            ["topRight"] = "Сверху справа",
            ["bottomLeft"] = "Снизу слева",
            ["bottomRight"] = "Снизу справа",
            ["onlyOwnData"] = "Показывается только ваше состояние. Позиций противников нет.",
            ["gsiMissing"] = "Игра ничего не присылает. Установлен ли cfg и перезапущен ли CS2?",
            ["audioError"] = "Не удалось включить звук",
            ["alreadyRunning"] = "VisionAssist Overlay уже запущен.",
            ["portBusy"] = "Порт занят. Закройте программу Companion, если она открыта.",
        },
        ["en"] = new()
        {
            ["health"] = "HEALTH",
            ["armor"] = "ARMOR",
            ["weapon"] = "WEAPON",
            ["round"] = "ROUND",
            ["money"] = "MONEY",
            ["waiting"] = "WAITING",
            ["noGame"] = "GAME CLOSED",
            ["menu"] = "MENU",
            ["freezetime"] = "FREEZE TIME",
            ["live"] = "ROUND",
            ["over"] = "ROUND OVER",
            ["warmup"] = "WARMUP",
            ["paused"] = "PAUSED",
            ["bomb"] = "BOMB",
            ["defusePhase"] = "DEFUSING",
            ["bombPlanted"] = "BOMB PLANTED",
            ["burning"] = "YOU ARE BURNING",
            ["blind"] = "YOU ARE BLIND",
            ["smoked"] = "IN SMOKE",
            ["defused"] = "DEFUSED",
            ["exploded"] = "BOMB EXPLODED",
            ["defuseYes"] = "ENOUGH TIME",
            ["defuseNo"] = "NOT ENOUGH",
            ["kit"] = "KIT",
            ["hasBomb"] = "YOU HAVE THE BOMB",
            ["helmet"] = "helmet",
            ["noWeapon"] = "none",
            ["left"] = "LEFT",
            ["right"] = "RIGHT",
            ["soundOff"] = "SOUND OFF",
            ["soundStarting"] = "STARTING",
            ["soundSilent"] = "NO AUDIO ARRIVING",
            ["soundNoBlocks"] = "METER DID NOT START",
            ["soundMono"] = "AUDIO IS MONO - NO DIRECTION",
            ["settings"] = "Settings",
            ["settingsHint"] = "Tapping Alt opens and closes this window",
            ["language"] = "Language",
            ["theme"] = "Colour preset",
            ["size"] = "Size",
            ["corner"] = "Position",
            ["opacity"] = "Opacity",
            ["sound"] = "Sound direction",
            ["sensitivity"] = "Sensitivity",
            ["on"] = "On",
            ["off"] = "Off",
            ["close"] = "Close",
            ["quit"] = "Quit",
            ["topLeft"] = "Top left",
            ["topRight"] = "Top right",
            ["bottomLeft"] = "Bottom left",
            ["bottomRight"] = "Bottom right",
            ["onlyOwnData"] = "Only your own state is shown. No enemy positions.",
            ["gsiMissing"] = "Nothing is arriving from the game. Is the cfg installed and CS2 restarted?",
            ["audioError"] = "Could not start audio",
            ["alreadyRunning"] = "VisionAssist Overlay is already running.",
            ["portBusy"] = "The port is in use. Close the Companion app if it is open.",
        },
    };

    public static string Get(string key)
    {
        if (Table.TryGetValue(Language, out var strings) && strings.TryGetValue(key, out string? value))
            return value;
        return Table["en"].TryGetValue(key, out string? fallback) ? fallback : key;
    }
}
